[unstable]
# On ajoute "alloc" ici pour que Rust compile la biblioth√®que pour ton OS
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-jc-os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"